language: php

php:
  - 5.5.9
  - 5.6
  - 7.0
  - hhvm

env:
  APP_ENV: testing
  CACHE_DRIVER: array
  SESSION_DRIVER: array
  QUEUE_DRIVER: sync
  DB_CONNECTION: sqlite

branches:
  only:
    - travis

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: 
  - vendor/bin/phpunit
